language: php

php:
  - '7.4'

before_script:
    - composer install --prefer-source --no-interaction

after_success:
  - bash <(curl -s https://codecov.io/bash)

script: vendor/bin/phpunit --coverage-clover coverage.xml

matrix:
    allow_failures:
        - php: 7.4

    fast_finish: true

notifications:
    on_success: never
    on_failure: always

env:
    global:
        - XDEBUG_MODE=coverage
